name: generateInputPaths
on: 
  #push:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      app_version:
        description: "The APP VERSION to be deployed"
        value: ${{ jobs.setup-build-publish-deploy.outputs.app_version }}
      matrix:
        description: "App_NAME"
        value: ${{ jobs.generateInputPaths.outputs.matrix }}

jobs:
  generateInputPaths:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - name: Generate matrix with all modules of WhatTheHack repository
      id: set-matrix
      run: |
        echo '::set-output name=matrix::["spring"]'
        #echo '::set-output name=matrix::["spring", "grafana"]'
 
  app_version:
    name: Get App_version
    needs: generateInputPaths
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.build.outputs.app_version }}
    strategy:
      #fail-fast: false
      matrix:
        path: ${{fromJson(needs.generateInputPaths.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tags
        shell: bash
        run: |
          version_file="deployment_version.yaml"
          echo "${{ matrix.path }}_version=$(yq -r .${{ matrix.path }}.version ${version_file})" >> $GITHUB_ENV
      - id: build
        run: |-
          IMAGE_VERSION=${${{ matrix.path }}_version}
          echo $IMAGE_VERSION
          echo "app_version=$IMAGE_VERSION" >> $GITHUB_OUTPUT
        
